require "rspec-expectations"
require 'spec/associations'

require 'rspec_rails3_validation_expectations/validation_expectations'
require 'rspec_rails3_validation_expectations/association_expectations'
require 'rspec_rails3_validation_expectations/other_expectations'